<?php

return [
    '/reports' => ['Admin/AdminModuleController', 'reports', ['methods' => ['GET'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
    '/reports/export' => ['Admin/AdminModuleController', 'exportReports', ['methods' => ['GET'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
    '/inventory' => ['Admin/AdminModuleController', 'inventory', ['methods' => ['GET'], 'roles' => [ROLE_ADMIN]]],
    '/inventory/adjust' => ['Admin/AdminModuleController', 'adjustStock', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/settings' => ['Admin/AdminModuleController', 'settings', ['methods' => ['GET'], 'roles' => [ROLE_SUPER_ADMIN]]],
    '/settings/update' => ['Admin/AdminModuleController', 'updateSettings', ['methods' => ['POST'], 'roles' => [ROLE_SUPER_ADMIN]]],
    '/admin/product' => ['Admin/AdminProductController', 'index', ['methods' => ['GET'], 'roles' => [ROLE_ADMIN]]],
    '/admin/product/create' => ['Admin/AdminProductController', 'create', ['methods' => ['GET'], 'roles' => [ROLE_ADMIN]]],
    '/admin/product/store' => ['Admin/AdminProductController', 'store', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/admin/product/edit' => ['Admin/AdminProductController', 'edit', ['methods' => ['GET'], 'roles' => [ROLE_ADMIN]]],
    '/admin/product/update' => ['Admin/AdminProductController', 'update', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/admin/product/delete' => ['Admin/AdminProductController', 'delete', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/admin/product/status' => ['Admin/AdminProductController', 'status', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/admin/product/import' => ['Admin/AdminProductController', 'import', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/admin/expense' => ['Admin/AdminExpenseController', 'index', ['methods' => ['GET'], 'roles' => [ROLE_ADMIN]]],
    '/admin/expense/store' => ['Admin/AdminExpenseController', 'store', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/admin/expense/update' => ['Admin/AdminExpenseController', 'update', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/admin/expense/delete' => ['Admin/AdminExpenseController', 'delete', ['methods' => ['POST'], 'roles' => [ROLE_ADMIN]]],
    '/admin/expense/export' => ['Admin/AdminExpenseController', 'export', ['methods' => ['GET'], 'roles' => [ROLE_ADMIN]]],
    '/admin/user' => ['Admin/AdminUserController', 'index', ['methods' => ['GET'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
    '/admin/user/create' => ['Admin/AdminUserController', 'create', ['methods' => ['GET'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
    '/admin/user/store' => ['Admin/AdminUserController', 'store', ['methods' => ['POST'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
    '/admin/user/edit' => ['Admin/AdminUserController', 'edit', ['methods' => ['GET'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
    '/admin/user/update' => ['Admin/AdminUserController', 'update', ['methods' => ['POST'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
    '/admin/user/delete' => ['Admin/AdminUserController', 'delete', ['methods' => ['POST'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
    '/admin/user/reset-password' => ['Admin/AdminUserController', 'resetPassword', ['methods' => ['POST'], 'roles' => [ROLE_SUPER_ADMIN, ROLE_ADMIN]]],
];
