<?php $grandTotal = array_sum(array_column($summary, 'total')); ?>
<div class="page-hero"><div class="page-title"><span class="eyebrow">STORE FINANCE</span><h2>Pengeluaran Toko</h2><p>Catat, koreksi, dan pantau biaya operasional toko.</p></div><a class="btn btn-outline-primary" href="<?= url('/admin/expense/export?' . http_build_query(['from' => $from, 'to' => $to])) ?>"><i class="ti ti-download"></i> Export CSV</a></div>
<div class="metric-grid mb-4">
  <div class="metric-card"><span>Total periode</span><strong><?= formatRupiah($grandTotal) ?></strong><small><?= e($from) ?> hingga <?= e($to) ?></small></div>
  <?php foreach (array_slice($summary, 0, 3) as $item): ?><div class="metric-card"><span><?= e(ucfirst($item['category'])) ?></span><strong><?= formatRupiah($item['total']) ?></strong><small>pengeluaran kategori</small></div><?php endforeach; ?>
</div>
<div class="row g-4 mb-4">
  <div class="col-xl-5"><div class="card surface"><div class="card-body"><div class="section-heading"><div><h3>Tambah Pengeluaran</h3><p>Nominal dicatat ke toko aktif.</p></div></div><form action="<?= url('/admin/expense/store') ?>" method="POST" class="row g-3"><?= csrf_field() ?>
    <div class="col-md-6"><label class="form-label">Kategori</label><select class="form-input" name="category" required><?php foreach ($categories as $category): ?><option value="<?= e($category) ?>"><?= e(ucfirst($category)) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-6"><label class="form-label">Tanggal</label><input class="form-input" type="date" name="expense_date" value="<?= date('Y-m-d') ?>" required></div>
    <div class="col-12"><label class="form-label">Nominal</label><input class="form-input" type="number" name="amount" min="1" placeholder="Contoh: 250000" required></div>
    <div class="col-12"><label class="form-label">Deskripsi</label><textarea class="form-input" name="description" rows="3" required></textarea></div>
    <div class="col-12"><button class="btn btn-primary w-100" type="submit"><i class="ti ti-plus"></i> Simpan pengeluaran</button></div>
  </form></div></div></div>
  <div class="col-xl-7"><div class="card surface"><div class="card-body"><div class="section-heading"><div><h3>Filter Laporan</h3><p>Batasi data yang ditampilkan.</p></div></div><form method="GET" action="<?= url('/admin/expense') ?>" class="row g-3">
    <div class="col-md-6"><label class="form-label">Dari</label><input class="form-input" type="date" name="from" value="<?= e($from) ?>"></div><div class="col-md-6"><label class="form-label">Sampai</label><input class="form-input" type="date" name="to" value="<?= e($to) ?>"></div>
    <div class="col-md-8"><label class="form-label">Kategori</label><select class="form-input" name="category"><option value="">Semua kategori</option><?php foreach ($categories as $category): ?><option value="<?= e($category) ?>" <?= $selectedCategory === $category ? 'selected' : '' ?>><?= e(ucfirst($category)) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4 d-flex align-items-end"><button class="btn btn-primary w-100"><i class="ti ti-filter"></i> Terapkan</button></div>
  </form></div></div></div>
</div>
<div class="card surface"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Tanggal</th><th>Kategori</th><th>Deskripsi</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>
<?php foreach ($expenses as $expense): ?><tr><td><?= e($expense['expense_date']) ?></td><td><span class="status-pill is-muted"><?= e(ucfirst($expense['category'])) ?></span></td><td><?= e($expense['description']) ?></td><td><strong><?= formatRupiah($expense['amount']) ?></strong></td><td><div class="d-flex gap-2">
  <details><summary class="btn btn-sm btn-outline-primary">Edit</summary><form action="<?= url('/admin/expense/update') ?>" method="POST" class="expense-edit-popover"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int) $expense['id'] ?>"><select class="form-input" name="category"><?php foreach ($categories as $category): ?><option value="<?= e($category) ?>" <?= $expense['category'] === $category ? 'selected' : '' ?>><?= e(ucfirst($category)) ?></option><?php endforeach; ?></select><input class="form-input" type="number" name="amount" value="<?= e((string) $expense['amount']) ?>" min="1"><input class="form-input" name="description" value="<?= e($expense['description']) ?>"><input class="form-input" type="date" name="expense_date" value="<?= e($expense['expense_date']) ?>"><button class="btn btn-primary btn-sm">Simpan</button></form></details>
  <form action="<?= url('/admin/expense/delete') ?>" method="POST" onsubmit="return confirm('Hapus pengeluaran ini?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int) $expense['id'] ?>"><button class="btn btn-sm btn-danger">Hapus</button></form>
</div></td></tr><?php endforeach; ?><?php if ($expenses === []): ?><tr><td colspan="5" class="text-center py-5 text-muted">Belum ada pengeluaran pada periode ini.</td></tr><?php endif; ?></tbody></table></div></div>
